[deps]
AdvancedVI = "b5ca4192-6429-45e5-a2d9-87aec30a685c"
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PosteriorDB = "1c4bc282-d2f5-44f9-b6d1-8c4424a23ad4"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
SlurmClusterManager = "c82cd089-7bf7-41d7-976b-6b5d413cbe0a"
StanLogDensityProblems = "a545de4d-8dba-46db-9d34-4e41d3f07807"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
AdvancedVI = "0.6.1"
Bootstrap = "2.4"
DataFrames = "1.8"
DataFramesMeta = "0.15"
Distributions = "0.25"
HDF5 = "0.17"
JLD2 = "0.6"
LinearAlgebra = "1.11"
LogDensityProblems = "2.2"
Plots = "1"
PosteriorDB = "0.6"
ProgressMeter = "1.11"
Random = "1.7"
Random123 = "1.7"
SlurmClusterManager = "1.1"
StanLogDensityProblems = "0.1"
StatsPlots = "0.15"
Suppressor = "0.2"
julia = "1.11"
